<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>M_S_Converter_Output_Compare</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>M&amp;S Converter Output Compare</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileCompare.Core\FileCompare.Core.csproj" />
  </ItemGroup>

</Project>
